In [20]:
import numpy as np

a = np.array([4, 10, 12, 23, -2, -1, 0, 0, 0, -6, 3, -7])


How many negative numbers are there?



In [5]:
len(a[a < 0])

4

How many positive numbers are there?



In [6]:
len(a[a>0])

5

How many even positive numbers are there?



In [9]:
len(a[(a>0) & (a%2 == 0)])

3

If you were to add 3 to each data point, how many positive numbers would there be?



In [21]:
a = a + 3
print(a)
len(a[a>0])

[ 7 13 15 26  1  2  3  3  3 -3  6 -4]


10

If you squared each number, what would the new mean and standard deviation be?



In [28]:
a = a **2


In [29]:
print(a.mean())
np.std(a)

101.0


186.64672512530188

In [30]:
a

array([ 49, 169, 225, 676,   1,   4,   9,   9,   9,   9,  36,  16])

A common statistical operation on a dataset is centering. This means to adjust the data such that the mean of the data is 0. This is done by subtracting the mean from each data point. Center the data set. See this link for more on centering.

Calculate the z-score for each data point. Recall that the z-score is given by:

In [39]:
aplus = a - a.mean()
za = (aplus - aplus.mean())/np.std(aplus)
za

array([-0.27860119,  0.36432463,  0.66435669,  3.08068625, -0.53577152,
       -0.51969838, -0.4929098 , -0.4929098 , -0.4929098 , -0.4929098 ,
       -0.34825149, -0.45540579])

In [50]:
# Setup 1
a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])




 Use python's built in functionality/operators to determine the following:
 
 Exercise 1 - Make a variable called sum_of_a to hold the sum of all the numbers in above list



In [51]:
sum_of_a = np.sum(a)
sum_of_a

55

 exercise 2 - Make a variable named min_of_a to hold the minimum of all the numbers in the above list



In [52]:
min_of_a = np.min(a)
min_of_a

1

 Exercise 3 - Make a variable named max_of_a to hold the max number of all the numbers in the above list

 

In [53]:
max_of_a = np.max(a)
max_of_a

10

Exercise 4 - Make a variable named mean_of_a to hold the average of all the numbers in the above list



In [54]:
mean_of_a = np.mean(a)
mean_of_a

5.5

 Exercise 5 - Make a variable named product_of_a to hold the product of multiplying all the numbers in the above list together



In [55]:
product_of_a = np.product(a)
product_of_a

3628800

 Exercise 6 - Make a variable named squares_of_a. It should hold each number in a squared like [1, 4, 9, 16, 25...]



In [57]:
squares_of_a = a ** 2
squares_of_a

array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

 Exercise 7 - Make a variable named odds_in_a. It should hold only the odd numbers



In [58]:
odds_in_a = a[a%2 == 1]
odds_in_a

array([1, 3, 5, 7, 9])

 Exercise 8 - Make a variable named evens_in_a. It should hold only the evens.

In [60]:
evens_in_a = a[a%2 == 0]
evens_in_a

array([ 2,  4,  6,  8, 10])

In [61]:
# Setup 2: Consider what it would take to find the sum, min, max, 
# average, sum, product, and list of squares for this list of two lists.
b = [
    [3, 4, 5],
    [6, 7, 8]
]

 Exercise 1 - refactor the following to use numpy. Use sum_of_b as the variable. **Hint, you'll first need to make sure that the "b" variable is a numpy array**




In [65]:
sum_of_b = np.sum(b)
sum_of_b

33

Exercise 2 - refactor the following to use numpy. 


In [67]:
min_of_b = np.min(b)
min_of_b

3

Exercise 3 - refactor the following maximum calculation to find the answer with numpy.


In [70]:
max_of_b = np.max(b)
max_of_b

8

Exercise 4 - refactor the following using numpy to find the mean of b




In [72]:
mean_of_b = np.mean(b)
mean_of_b

5.5

Exercise 5 - refactor the following to use numpy for calculating the product of all numbers multiplied together.




In [74]:
product_of_b = np.product(b)
product_of_b

20160

 Exercise 6 - refactor the following to use numpy to find the list of squares 





In [76]:
squares_of_b = a ** 2
squares_of_b

array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

 Exercise 7 - refactor using numpy to determine the odds_in_b





In [77]:
odds_in_b = a[a%2==1]
odds_in_b

array([1, 3, 5, 7, 9])

 Exercise 8 - refactor the following to use numpy to filter only the even numbers




In [78]:
evens_in_b = a[a%2==0]
evens_in_b

array([ 2,  4,  6,  8, 10])

 Exercise 9 - print out the shape of the array b.



In [82]:
np.shape(a)

(10,)

 Exercise 10 - transpose the array b.



In [83]:
np.transpose(b)

array([[3, 6],
       [4, 7],
       [5, 8]])

 Exercise 11 - reshape the array b to be a single list of 6 numbers. (1 x 6)



In [84]:
np.reshape(b, 6)

array([3, 4, 5, 6, 7, 8])

 Exercise 12 - reshape the array b to be a list of 6 lists, each containing only 1 number (6 x 1)

In [86]:
np.reshape(b, )

ValueError: cannot reshape array of size 6 into shape (0,)

In [ ]:
#Setup 3
c = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
]




 HINT, you'll first need to make sure that the "c" variable is a numpy array prior to using numpy array methods.
 
 Exercise 1 - Find the min, max, sum, and product of c.



 Exercise 2 - Determine the standard deviation of c.



 Exercise 3 - Determine the variance of c.



 Exercise 4 - Print out the shape of the array c



 Exercise 5 - Transpose c and print out transposed result.



 Exercise 6 - Get the dot product of the array c with c. 



 Exercise 7 - Write the code necessary to sum up the result of c times c transposed. Answer should be 261



 Exercise 8 - Write the code necessary to determine the product of c times c transposed. 
 
 Answer should be 131681894400.




In [ ]:
## Setup 4
d = [
    [90, 30, 45, 0, 120, 180],
    [45, -90, -30, 270, 90, 0],
    [60, 45, -45, 90, -45, 180]
]



 Exercise 1 - Find the sine of all the numbers in d



 Exercise 2 - Find the cosine of all the numbers in d



 Exercise 3 - Find the tangent of all the numbers in d



 Exercise 4 - Find all the negative numbers in d



 Exercise 5 - Find all the positive numbers in d



 Exercise 6 - Return an array of only the unique numbers in d.



 Exercise 7 - Determine how many unique numbers there are in d.



 Exercise 8 - Print out the shape of d.



 Exercise 9 - Transpose and then print out the shape of d.



 Exercise 10 - Reshape d into an array of 9 x 2